# Site settings
title: K-D-G-Blog
email: grayshonprogrammer@gmail.com
description: A blog by K-D-G
baseurl: "/K-D-G-Blog"
twitter_username: Kieran_Grayshon
avatar: "https://pbs.twimg.com/profile_images/1017834568848760833/L9VxsqtX_400x400.jpg" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "K-D-G" # Set default author name
      categories: "Computer Science"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
